# Generated by Django 4.0 on 2021-12-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amaliyot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Amaliyot',
            },
        ),
        migrations.CreateModel(
            name='Konfirensiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Konfirensiya',
            },
        ),
        migrations.CreateModel(
            name='Labartoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Labartoriya',
            },
        ),
        migrations.CreateModel(
            name='Maruza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Maruza',
            },
        ),
        migrations.CreateModel(
            name='MustaqilTalim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'MustaqilTalim',
            },
        ),
        migrations.CreateModel(
            name='OAK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'OAK',
            },
        ),
        migrations.CreateModel(
            name='Scopus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fayl', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Scopus',
            },
        ),
    ]
