# Generated by Django 4.0 on 2021-12-27 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amaliyot',
            old_name='fayl',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='konfirensiya',
            old_name='fayl',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='labartoriya',
            old_name='fayl',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='maruza',
            old_name='fayl',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='mustaqiltalim',
            old_name='fayl',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='oak',
            old_name='fayl',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='scopus',
            old_name='fayl',
            new_name='file',
        ),
    ]
