# Generated by Django 4.0 on 2021-12-27 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_page_pagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='maruza',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.page'),
        ),
    ]
