# Generated by Django 4.0 on 2021-12-28 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_marpage_alter_maruza_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(default='Amaliyot', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Amaliyot',
            },
        ),
        migrations.AlterModelOptions(
            name='amaliyot',
            options={},
        ),
        migrations.AlterModelOptions(
            name='marpage',
            options={'verbose_name_plural': 'Maruza'},
        ),
        migrations.AlterModelOptions(
            name='maruza',
            options={},
        ),
        migrations.AddField(
            model_name='amaliyot',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.amapage'),
        ),
    ]
