# Generated by Django 4.0.3 on 2022-03-20 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_eye'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now, verbose_name='свидание')),
                ('count', models.IntegerField(default=0, verbose_name='Количество посещений сайта')),
            ],
            options={
                'verbose_name': 'Статистика ежедневных посещений сайта',
                'verbose_name_plural': 'Статистика ежедневных посещений сайта',
            },
        ),
        migrations.CreateModel(
            name='Userip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='Айпи адрес')),
                ('count', models.IntegerField(default=0, verbose_name='Визиты')),
            ],
            options={
                'verbose_name': 'Доступ к информации о пользователе',
                'verbose_name_plural': 'Доступ к информации о пользователе',
            },
        ),
        migrations.CreateModel(
            name='VisitNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='Всего посещений сайта')),
            ],
            options={
                'verbose_name': 'Всего посещений сайта',
                'verbose_name_plural': 'Всего посещений сайта',
            },
        ),
        migrations.DeleteModel(
            name='Eye',
        ),
    ]
